
hesai_node:
  ros__parameters:
      udp_port: 2368
      ptc_port: 9347
      host_ip_address: 10.32.1.100
      device_ip_address: 10.32.1.201
      correction_file_path: "package://hesai_ros_driver/correction/pandar_xt32_angle_correction.csv"
      firetimes_path: "package://hesai_ros_driver/correction/pandar_xt32_firetime_correction.csv"
      lidar_type: "PandarXT32"
      distance_correction_lidar_type: ""
      source_type: 1
      standby_mode: 0
      speed: 1200
      fov_start: -1
      fov_end: -1
      transform:
        x: 0.0
        y: 0.0
        z: 0.0
        roll: 0.0
        pitch: 0.0
        yaw: 0.0
      frame_id: "lidar_link"
      topics:
        packet: "/lidar/packets"
        point_cloud: "/points"
        status: "/lidar/status"
      publish_packet: false
      publish_pointcloud: true
      publish_status: true
      enable_packet_loss_tool: false
